version: 2

aliases:
  # Workflow filters
  - &filter-only-master
    branches:
      only: master

defaults: &defaults
  docker:
    - image: circleci/node:12

jobs:
  build_plugin:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
          - yarn-packages-{{ checksum "yarn.lock" }}
      - run:
          name: Install dependencies
          command: |
            yarn install --pure-lockfile
      - run:
          name: Build and test frontend
          command:  |
            npx grafana-toolkit plugin:ci-build
            npx grafana-toolkit plugin:ci-build --finish
      - save_cache:
          paths:
            - node_modules
          key: yarn-packages-{{ checksum "yarn.lock" }}
      - persist_to_workspace:
          root: .
          paths:
            - ci
  build_docs:
    <<: *defaults
    steps:
    - checkout
    - restore_cache:
        keys:
        - yarn-packages-{{ checksum "yarn.lock" }}
    - run:
        name: Install dependencies
        command: |
          yarn install --pure-lockfile
    - run:
        name: Build Docs
        command: |
          mkdir ci # Avoid error if not exists
          ./node_modules/.bin/grafana-toolkit plugin:ci-docs
    - save_cache:
        paths:
        - node_modules
        key: yarn-packages-{{ checksum "yarn.lock" }}
    - persist_to_workspace:
        root: .
        paths:
        - ci

  package:
    <<: *defaults
    steps:
    - checkout
    - attach_workspace:
        at: .
    - restore_cache:
        keys:
        - yarn-packages-{{ checksum "yarn.lock" }}
    - run:
        name: Package Distribution
        command: |
          yarn install --pure-lockfile
          ./node_modules/.bin/grafana-toolkit plugin:ci-package
    - persist_to_workspace:
        root: .
        paths:
        - ci/jobs/package
        - ci/packages
        - ci/dist
        - ci/grafana-test-env

  test_integration:
    docker:
    - image: circleci/node:12-browsers
    steps:
    - checkout
    - attach_workspace:
        at: .
    - restore_cache:
        keys:
        - yarn-packages-{{ checksum "yarn.lock" }}
    - run:
        name: Setup Grafana (local install)
        command: |
          wget https://dl.grafana.com/oss/release/grafana_6.6.1_amd64.deb
          sudo apt-get install -y adduser libfontconfig1
          sudo dpkg -i grafana_6.6.1_amd64.deb
          sudo apt-get install locate
          sudo updatedb
          sudo locate grafana
          sudo cat /etc/grafana/grafana.ini
          sudo echo ------------------------
          sudo cp ci/grafana-test-env/custom.ini /usr/share/grafana/conf/custom.ini
          sudo cp ci/grafana-test-env/custom.ini /etc/grafana/grafana.ini
          sudo service grafana-server start
          sudo grafana-cli --version
    - run:
        name: Run e2e tests
        command: |
          yarn install --pure-lockfile
          ./node_modules/.bin/grafana-toolkit plugin:ci-test
    - persist_to_workspace:
        root: .
        paths:
        - ci/jobs/test_integration
    - store_test_results:
        path: ci/jobs/test_integration
    - store_artifacts:
        path: ci/jobs/test_integration

  report:
    docker:
    - image: circleci/node:12
    steps:
    - checkout
    - attach_workspace:
        at: .
    - restore_cache:
        keys:
        - yarn-packages-{{ checksum "yarn.lock" }}
    - run:
        name: Toolkit report
        command: |
          yarn install --pure-lockfile
          ./node_modules/.bin/grafana-toolkit plugin:ci-report
    - store_artifacts:
        path: ci

  publish_github_release:
    <<: *defaults
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "dc:60:ab:c7:2d:8c:82:50:2a:2a:97:1a:c0:66:83:14"
      - attach_workspace:
          at: .
      - restore_cache:
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}
      - run:
          name: "Publish Release on GitHub"
          command: ./node_modules/.bin/grafana-toolkit plugin:github-publish

workflows:
  version: 2
  plugin_workflow:
    jobs:
      - build_plugin
      - build_docs
      - package:
          requires:
            - build_plugin
            - build_docs
      - test_integration:
          requires:
            - package
      - report:
          requires:
            - test_integration
      - approve_release:
          type: approval
          requires:
            - report
          filters: *filter-only-master
      - publish_github_release:
          requires:
            - approve_release
          filters: *filter-only-master
